#!/usr/bin/env python3

import argparse
import pprint
from termcolor import cprint, colored
import atexit
import subprocess
import os
import sys
import re

from utils.sql import sql
from utils import utils

def cleanup(file):
    ###	clean up
    os.remove(file)


def main():
    pp = pprint.PrettyPrinter(indent=4)

    parser = argparse.ArgumentParser("get more info about findings")
    parser.add_argument('-s', '--service', dest='service', required=True, \
        help="Service to investigate.")
    parser.add_argument('-v', '--verbose', dest='v', action='store_true', \
        help="Make output more verbose.")
    args = parser.parse_args()

    # check for existing pid file
    pidfile = '/tmp/store.pid.run'
    if os.path.exists(pidfile):
        eprint(colored("PID file exists.  Is store already running?", "red", attrs=['bold']))
        raise Exception("Verify if the program is currently running and/or delete the file at {}".format(pidfile))

    # register the cleanup function to run at exit
    atexit.register(cleanup, pidfile)

    # set up the sql object
    sqlu = sql.sqlutils()
    # get the config info
    conf = sqlu.load_config()
    u = utils.utils()

    ### set pid file
    with open(pidfile, 'w') as pidf:
        pidf.write(str(os.getpid()))

    # start logging (?)

    svc_ports = {}
    svc_ports['ftp'] = "21"
    svc_ports['http'] = "80,8000,8080"
    svc_ports['https'] = "443,8443"
    svc_ports['mssql'] = "1433"
    svc_ports['mysql'] = "3306"
    svc_ports['oracle'] = "1521"
    svc_ports['postgre'] = "5432"
    svc_ports['pclpjl'] = "9100"
    svc_ports['postgres'] = "5432"
    svc_ports['rdp'] = "3389"
    svc_ports['rsh'] = "-p514"
    svc_ports['smtp'] = "25,965"
    svc_ports['ssh'] = "22"
    svc_ports['telnet'] = "23"
    svc_ports['vnc'] = "5800,5900,5901,5902,5903,5904,5905,5906,5907,5908,5909,5910"
    svc_ports['vpn'] = "1701,1723"

    print("Available services: {}".format("|".join(svc_ports.keys())))
    # take 'proto' in from argv (?) and verify it is valid
    hosts = []
    # get all of the ips in the database that reported the relevant port open
    if re.search(r"(?:{})".format("|".join(svc_ports.keys())), args.service) \
        is not None:
        if args.v: print("Service ({}) matched an expected service."\
            .format(args.service))
        if svc_ports[args.service].count(',') > 0:
            if args.v: print("Service has more than one port: {}"\
                .format(svc_ports[args.service]))
            ports = svc_ports[args.service].split(',')
            for p in ports:
                hosts.extend(sqlu.get_hosts_by_port(p))
        else:
            hosts = sqlu.get_hosts_by_port(svc_ports[args.service])
    # set the nmap path
    nmap = u.which('nmap')
    if nmap is None and conf['nmap_path'] is None:
        print("You must install nmap or update the config with the path.")
        exit(1)
    # loop through the list of targets and grab the banners for the protocol
    for h in hosts:
        subprocess.call([nmap, "-sT", "-p", svc_ports[args.service], \
            "--script", "banner", '--reason', h])
    # check if the banner is stored
    #   if it is stored,
    #   check if the one we just grabbed is the same as the stored one



if __name__=='__main__':
    main()
